version: '3.8'

services:
  seq:
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    restart: always
    ports:
      - "5340:80"
    
  mssql:
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - cmessaging-mssql-data:/var/opt/mssql

  cassandra:
    container_name: cassandra
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    ports:
      - "9042:9042"
    restart: always
    volumes:
      - cmessaging-cassandra-data:/var/lib/cassandra

  redis:
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - cmessaging-redis-data:/data

  messaging.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5001:80"
    restart: always

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ASPNETCORE_URLS=http://+:80
      - CLIENT_APP={APP_EXTERNAL_DNS_NAME_OR_IP}:5500
      - SEED_DATABASE=false
    ports:
      - "5000:80"
    restart: always

  clientapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ASPNETCORE_URLS=http://+:80
      - IDENTITY_URL={APP_EXTERNAL_DNS_NAME_OR_IP}:5000
    ports:
      - "5500:80"
    restart: always

volumes:
  cmessaging-cassandra-data:
    external: false
  cmessaging-mssql-data:
    external: false
  cmessaging-redis-data:
    external: false
