version: '3.8'

services:
  seq:
    image: datalust/seq:latest

  cassandra:
    image: cassandra:latest

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest

  messaging.api:
    image: ${DOCKER_REGISTRY-}messagingapi
    build:
      context: .
      dockerfile: Services/Messaging/Messaging.API/Dockerfile
  
  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile

networks:
  default:
    external:
      name: cmessaging
