name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup network
      run: docker network create cmessaging
    - name: Run docker-compose
      run: docker-compose -f src/docker-compose.yml up&
    - name: Wait for setup
      run: sleep 6m
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Run tests
      run: dotnet test src/Services/Messaging/Messaging.Test
    - name: Exit
      run: docker-compose -f src/docker-compose.yml down

